language: node_js
node_js:
  - "node"
services:
  - postgresql 

before_script:
  - npm install
  - psql -c 'create database questioner_test;' -U postgres
script:
  - npm test
after_success:
- npm run coveralls